# Generated by Django 3.2.7 on 2021-09-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
